version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: wednesday
    time: "03:00"
    timezone: Europe/London
  groups:
    pip:
      patterns:
        - "*"
  open-pull-requests-limit: 15
  allow:
    - dependency-type: "all"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    day: thursday
    time: "03:00"
    timezone: Europe/London
  groups:
    docker:
      patterns:
        - "*"
  open-pull-requests-limit: 15
  allow:
    - dependency-type: "all"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: tuesday
    time: "03:00"
    timezone: Europe/London
  groups:
    actions:
      patterns:
        - "*"
  open-pull-requests-limit: 15
  allow:
    - dependency-type: "all"
