# Default values for laa-court-data-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: laa-court-data-api-app
fullnameOverride: laa-court-data-api-app

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  namespace: laa-court-data-api-staging
  annotations:
    kubernetes.io/ingress.class: modsec01
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecAction "id:900200,phase:1,nolog,pass,t:none,setvar:tx.allowed_methods=GET HEAD POST OPTIONS PUT PATCH DELETE"
    external-dns.alpha.kubernetes.io/set-identifier: laa-court-data-api-app-laa-court-data-api-staging-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
  hosts:
    - host: laa-court-data-api-staging.apps.live.cloud-platform.service.justice.gov.uk
      paths:
        - path: /
          pathType: Prefix

court_data_adaptor:
  url: https://stage.court-data-adaptor.service.justice.gov.uk/