# Default values for laa-court-data-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: laa-court-data-api-app
fullnameOverride: laa-court-data-api-app

securityContext:
   capabilities:
     drop:
     - ALL
   readOnlyRootFilesystem: true
   runAsNonRoot: true
   runAsUser: 10000
   allowPrivilegeEscalation: false

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 128Mi

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  namespace: laa-court-data-api-production
  annotations:
    kubernetes.io/ingress.class: modsec01
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecAction "id:900200,phase:1,nolog,pass,t:none,setvar:tx.allowed_methods=GET HEAD POST OPTIONS PUT PATCH DELETE"
    external-dns.alpha.kubernetes.io/set-identifier: laa-court-data-api-app-laa-court-data-api-production-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
  tls:
    - hosts:
      - laa-court-data-api-production.apps.live.cloud-platform.service.justice.gov.uk
    - hosts:
      - court-data-api.service.justice.gov.uk
      secretName: laa-court-data-api-production-cert
  hosts:
    - host: laa-court-data-api-production.apps.live.cloud-platform.service.justice.gov.uk
      paths:
        - path: /
          pathType: Prefix    
    - host: court-data-api.service.justice.gov.uk
      paths:
        - path: /
          pathType: Prefix

court_data_adaptor:
  url: https://court-data-adaptor.service.justice.gov.uk/