# Default values for laa-court-data-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: laa-court-data-api-app
fullnameOverride: laa-court-data-api-app

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: modsec01
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
    external-dns.alpha.kubernetes.io/set-identifier: laa-court-data-api-app-ingress-laa-court-data-api-staging-blue
    external-dns.alpha.kubernetes.io/aws-weight: "100"
  hosts:
    - host: laa-court-data-api-staging.court-data-api.service.justice.gov.uk
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

court_data_adaptor:
  url: https://stage.court-data-adaptor.service.justice.gov.uk/